version: "3.9"
services:
  fib:
    build:
      context: .
      dockerfile: fib.Dockerfile
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - 8080:8080
    depends_on:
      - zipkin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
