receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging:

  zipkin:
    endpoint: "${OTEL_EXPORTER_ZIPKIN_ENDPOINT}"
    format: proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin]
